
#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org:
      springframework:
        web: WARN
        security: DEBUG

    com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    context-path: /auth
