example.property: "I AM THE DEFAULT"
spring.jpa.database: "mysql"
spring.datasource.platform:  "mysql"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://127.0.0.1:3306/eagle_eye_local?useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT"
spring.datasource.username: "root"
spring.datasource.password: "{cipher}247758a5a2e6f27e12fc80a4091fda3b75aafb65403076ada09b26894816428c"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQLDialect"
redis.server: "127.0.0.1"
redis.port: "6379"