GET {{host_licenses}}/v1/licenses
Authorization: Bearer {{token}}

### 1/3 Sorry no licensing information currently available
GET {{host_licenses}}/v1/organizations/e254f8c-c442-4ebe-a82a-e2fc1d1ff78a/licenses/
Authorization: Bearer {{token}}
tmx-correlation-id: TEST-CORRELATION-ID